### ISSUE TITLE
请问下,如果想改变tabs上的字体大小 tabs高度 还有横线位置要在什么地方

### ISSUE THREAD

**Issue by JonsonHI** [Slowyn/react-native-underline-tabbar#1]

**Comment by Slowyn** [comment]
Could you describe issue in english, please?

**Comment by JonsonHI** [comment]
Excuse me, if you want to change the font size on the label tag height and horizontal position in what place

**Comment by JonsonHI** [comment]
changes Line width and font size

**Comment by Slowyn** [comment]
You can use `tabBarTextStyle` property
