### ISSUE TITLE
outputRange must have at least 2 elements

### ISSUE THREAD

**Issue by AndsteLyc** [Slowyn/react-native-underline-tabbar#15]
Hi, I have a problem here.
Can you help me :bug:?

When ScrollableTabView had only one child(The number of children is dynamic)，TabBar don't work.
```
<ScrollableTabView
       tabBarActiveTextColor={THEME_COLOR.main}
       renderTabBar={() => <TabBar underlineColor={THEME_COLOR.main} />}
>
      <View tabLabel={{label: "Page #1"}}/>
</ScrollableTabView>
```
![](http://data.andste.cc/developers/web/temp/images/QQ20171030-235609.png)

**Comment by Slowyn** [comment]
Hi @AndsteLyc! Thank you for reporting. I'll fix it asap.

**Comment by AndsteLyc** [comment]
Hi @Slowyn . I submitted a pull request, did you look like this?

Sorry,The code for that pull request is a bit of a problem.

PS: Sorry, I will only be a little bit of English. All of the above are translated by Google

**Comment by anonrig** [comment]
I'm having this issue. @Slowyn
