### ISSUE TITLE
bug？inputRange must be monotonically

### ISSUE THREAD

**Issue by KingBarbarian** [Slowyn/react-native-underline-tabbar#20]
![image](https://user-images.githubusercontent.com/31871781/34428716-9fb11142-ec8a-11e7-85fc-78f024c3468a.png)

This api is paging query, i set pageSize=10 no problem,but i set pageSize=20 this error occurred！

**Comment by Slowyn** [comment]
@KingBarbarian Which version of library do you use? It should have been fixed in newest version.
