### ISSUE TITLE
ScrollView Restore

### ISSUE THREAD

**Issue by KingBarbarian** [Slowyn/react-native-underline-tabbar#21]
![demo](https://user-images.githubusercontent.com/31871781/34552512-dbd72d88-f15c-11e7-98c8-162dc0f8c20b.gif)
When the page slides,Tab don't follow to locate？I am Chinese,English is not good,Sorry,Thank you！

**Comment by Slowyn** [comment]
Thanks for reporting. Can you provide code which cause such behavior?

**Comment by Slowyn** [comment]
Also, tell what version do you use.
