### ISSUE TITLE
如何定制badge的形状

### ISSUE THREAD

**Issue by hdhdsu** [Slowyn/react-native-underline-tabbar#24]
项目中badge是圆形，怎么改成圆形

**Comment by Slowyn** [comment]
You can pass your own styles to badge using `badgeBubble`. Something like this
```js
<TabBar tabStyles={{badgeBubble: {/* your styles here */}}}/>
```
P.S. Please, create issues in English. I (author) am not chinese. Google translate has helped me, but this shouldn't be regular practice.
