### ISSUE TITLE
initialPage={parseInt(this.state.index)}   if index is five or six ,it will hide tab,how scroll this tab

### ISSUE THREAD

**Issue by hdhdsu** [Slowyn/react-native-underline-tabbar#25]
if enter from other page , if index is five or six ,it will hide tab,how scroll this tab

code:

      <ScrollableTabView
                    initialPage={parseInt(this.state.index)}
                    tabBarActiveTextColor='red'
                    tabBarTextStyle={{ fontSize: 30, color: 'white' }}

                    renderTabBar={() => (
                        <TabBar underlineColor='red' backgroundColor='white' tabStyles={{ badgeBubble: styles.circle }} />
                    )}
                >

![image](https://user-images.githubusercontent.com/19816799/35616424-20d0b20c-06b0-11e8-909b-1ab9730c66c9.png)

PS : sorry,my English is not good

**Comment by Slowyn** [comment]
Currently Tabbar can't be manually scrolled to some position :(
But I can fix initial mount of tabbar. I'll publish update as soon as possible.
Thanks for reporting!

**Comment by Slowyn** [comment]
Fix in 029b012599e8cc5f6db3d2114f749108a0407bc4
Please, update to latest version to solve your issue.
