### ISSUE TITLE
Not showing Advanced Tabs in Android

### ISSUE THREAD

**Issue by parmeet9891** [Slowyn/react-native-underline-tabbar#26]
In IOS, its working fine
But in android, it gives error in this area : 

    `const containerStyle = {
    paddingHorizontal: 20,
    paddingVertical: 5,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: **styles.backgroundColor**,
    opacity: **styles.opacity**,
    transform: [{ scale: **styles.opacity** }],
  };`

and says **undefined is not an object (evaluating 'styles.textColor')**
And when i put any random colors here, the error will disappear but shows nothing (no tabs).

**Comment by Slowyn** [comment]
Hi @parmeet9891! That's pretty interesting catch. The trick is that problem doesn't appear in Debugger mode. I've researched and found out that this code
```js
[...Array(6).keys()]
```
doesn't work properly and returns an empty array. I have fixed the problem into [example repository](https://github.com/Slowyn/UnderlineTabBarExample) and a bit refactored code increasing the readability.
Thanks for reporting!
