### ISSUE TITLE
引进来用之后tab标签都没了

### ISSUE THREAD

**Issue by wakeupmycat** [Slowyn/react-native-underline-tabbar#28]

**Comment by Slowyn** [comment]
**Issues** are welcome. Please add a screenshot of bug and code snippet. Quickest way to solve issue is to reproduce it on one of the examples.

Please attach video or gif to PR's and issues it is super helpful.
Also, please, use English for commincation.

**Comment by Slowyn** [comment]
Closed due to inactivity.
