### ISSUE TITLE
tab scroll problem

### ISSUE THREAD

**Issue by hdhdsu** [Slowyn/react-native-underline-tabbar#29]
if enter from other page , will happen this
![1520822711 1](https://user-images.githubusercontent.com/19816799/37263308-7adba3fa-25e2-11e8-8657-8b17ab9d19d5.png)

**Comment by Slowyn** [comment]
Hi @hdhdsu, thanks for reporting!
Do you load new dataset for badges while you enter on your page?

**Comment by hdhdsu** [comment]
of course 


            return (
                   <View style={styles.container}>
                        <ScrollableTabView
                            initialPage={parseInt(this.state.index)}
                            tabBarActiveTextColor='red'
                            tabBarTextStyle={{ fontSize: 30, color: 'white' }}
                            renderTabBar={() => (
                        <TabBar underlineColor='red' backgroundColor='white' tabStyles={{ badgeBubble: 
                      styles.circle }} />
                    )}
                >           
                    <InquiryOrderView tabLabel={{ label: "All Orders" }} status='' nav={this.navigate} updateCount={() => this.getOrderCount()} />    
            
                    <InquiryOrderView tabLabel={{ label: "Wait", badge: this.state.toBepaidCount }} status='0' nav={this.navigate} updateCount={() => this.getOrderCount()} />
             
                    <InquiryOrderView tabLabel={{ label: "Get Paid", badge: this.state.toBeConfimCount }} status='5' nav={this.navigate} updateCount={() => this.getOrderCount()} />
                   
                    <InquiryOrderView tabLabel={{ label: "Processed", badge: this.state.toBeShipperCount }} status='1' nav={this.navigate} updateCount={() => this.getOrderCount()} />
                  
                    <InquiryOrderView tabLabel={{ label: "Sent", badge: this.state.toBeConfirmReceiptCount }} status='2' nav={this.navigate} updateCount={() => this.getOrderCount()} />
                   
                    <InquiryOrderView tabLabel={{ label: "Return", badge: this.state.returnCount }} status='4' nav={this.navigate} updateCount={() => this.getOrderCount()} />
                </ScrollableTabView>

            </View >
        );

It was ok last week ,but there was a problem today.

**Comment by Slowyn** [comment]
Probably it happens because of  tab's resizing. I'll try to fix this problem this week.

**Comment by hdhdsu** [comment]
It is ok when I cancel badge,but It is same problem when I set badge.

**Comment by hdhdsu** [comment]
When I get count from net,and set count to badge,it is happen same problem,but if I set badge directly,it is ok

**Comment by Slowyn** [comment]
Hi @hdhdsu!
I've published update in which I've improved rerender mechanism. Please, update and report me if your problem is still actual.
