### ISSUE TITLE
error layout in the landscape mode

### ISSUE THREAD

**Issue by malonguwa** [Slowyn/react-native-underline-tabbar#30]
@Slowyn hi thanks for the tabber~ nice job~ Do you got chance to test the scrollable Tab on the landscape mode for ios or android (I mean switch from vertical mode to landscape mode) ? it is not positioned correctly.
I am using react-native-scrollable-tab-view: 0.8.0, and your latest version.
import TabBar from "react-native-underline-tabbar";

when I using the TabBar 
```
<ScrollableTabView
              tabBarActiveTextColor="#53ac49"
              renderTabBar={() => <TabBar underlineColor="#53ac49" />}> <-- flow error in <TabBar/> tag
       <Page tabLabel={{label: "Page #1"}} label="Page #1"/>
                   ......          
</ScrollableTabView>

```
, the flow gives lots type error. I will try to post a screenShot of it when I got time.

**Comment by Slowyn** [comment]
Hi @malonguwa! Thanks for reporting!
You are right, currently tabbar isn't well tested for landscape orientation. It will be the next thing I will improve. Also, thanks for feedback on Flow as a user! I'll take a look and will fix errors.

**Comment by malonguwa** [comment]
@Slowyn Thanks for the reply! much appreciated! the react-native-scrollable-tab-view seems like there is no any maintenance after its v0.8.0, and I think most people is using 0.8.0 now. May I ask which react-native-scrollable-tab-view version your TabBar is based on? If you using 0.8.0~ maybe is good idea to post on the react-native-scrollable-tab-view, and let all the people know you can fix some the issues they got~ well done~ by the way~

**Comment by Slowyn** [comment]
Initially it was based on v0.5.* versions. There were not breaking changes in tabbar API since then and it works well with the latest versions. I always test on latest version (v0.8.0).

**Comment by Slowyn** [comment]
Hi @malonguwa!
![image](https://user-images.githubusercontent.com/7250604/39560390-e785a416-4ec7-11e8-9cfe-2b9412d02a30.png)
Is this acceptable layout?

**Comment by malonguwa** [comment]
@Slowyn  sorry for the late reply, nice work ~ this is looks good!
