### ISSUE TITLE
[iOS] Landscape mode can not scroll the tab

### ISSUE THREAD

**Issue by malonguwa** [Slowyn/react-native-underline-tabbar#31]
@Slowyn Thanks for the amazing lib, please take a look the issue i found,

1. [ios] When rotate the app into landscape, the scrollableTab can not be scrolled anymore.
Please refer to the gif for more info.

2. [android and ios] Is that possible to add a auto-focus feature when rotate screen? for example, in android if i have 10 tabs, in landscape mode we click tab number 10, and when switch to vertical mode we can auto scroll to the position of tab number 10 rather than manually scroll to the most right to find it.

react-native: 0.55.3
react-native-scrollable-tab-view:0.8.0 (latest)
react-native-underline-tabbar: latest
iOS simulator-iPhone 8

![landscapecannotdrag](https://user-images.githubusercontent.com/2183780/40410335-1f756f90-5ea0-11e8-9d47-e00e4b980716.gif)

**Comment by Slowyn** [comment]
@malonguwa Hi! Thanks for awesome issue description. I'll take a look as soon as possible, but probably I'll be busy in next couple of weeks.

**Comment by Slowyn** [comment]
Hi @malonguwa! That was a pretty huge delay, heh :)
I've fixed this issue in the latest version. Please, comment below so I can close the issue. Or I'll close issue by myself in several days.

**Comment by Slowyn** [comment]
@malonguwa Feel free to reopen issue if problem is still relevant for you.
But now, I'll close the issue.
