### ISSUE TITLE
多个组件一起使用,如何动态高度?Multiple components used together, how dynamic height?

### ISSUE THREAD

**Issue by shaoting0730** [Slowyn/react-native-underline-tabbar#33]
如图:
for example:
![33ed987c32b911e7e2fe07983d084cc1](https://user-images.githubusercontent.com/14305431/44188844-8674ec80-a152-11e8-9ca9-f7718a416ba1.jpg)
![a4e8107c60a729892094eb02cb346216](https://user-images.githubusercontent.com/14305431/44188852-8ffe5480-a152-11e8-8e03-8beeaf73d5d6.jpg)
![0ab46ec39c35bf9ae6dc3b8a92598ea0](https://user-images.githubusercontent.com/14305431/44188857-942a7200-a152-11e8-8e92-66fc20f56390.jpg)

**Comment by Slowyn** [comment]
Hello @pheromone! I am sorry, but I didn't get the problem. Could explain it more clearly, please?

**Comment by shaoting0730** [comment]
我的意思是:当我从模块1划到模块2的时候,高度会增加.
但我从模块2回到模块1的时候,高度不会改变.会多出一块空白.
如图中红色框
I mean: when I cross from module 1 to module 2, the height increases.
But when I go back from module 2 to module 1, the height doesn't change.This creates an extra blank space.The red box is shown

**Comment by Slowyn** [comment]
Honestly, I'm not sure. But the problem seems to be not related with tabbar.  You can check your layout with inbuild inspector.
