### ISSUE TITLE
Rounded Tab Underline

### ISSUE THREAD

**Issue by r-arvind** [Slowyn/react-native-underline-tabbar#34]
Is it possible for the tab underline bar to have rounded corners???

**Comment by Slowyn** [comment]
Hi @r-arvind!
Unfortunately, the current implementation doesn't allow to changes styles for underline.
You can create PR for this functionality if you wish :)

**Comment by edo1493** [comment]
Do you guys have any ideas on how this could be implemented? BordeRadius seems not to work on a transform. :(

**Comment by r-arvind** [comment]
@edo1493 I haven't been able to figure out how to do this.
But I think native base has scrollable tabs which support rounded corners. I haven't tried it out though.
