### ISSUE TITLE
Custom views

### ISSUE THREAD

**Issue by mozamonkey** [Slowyn/react-native-underline-tabbar#35]
Does this tab bar let us add new scenes on each click? For example, could i have flat lists with views, buttons, text , etc?

**Comment by Slowyn** [comment]
Do you mean can You dynamically ad tab views? Sure. You can just pass your views to the component.
```js
        <ScrollableTabView
          tabBarUnderlineColor="#53ac49"
          tabBarActiveTextColor="#53ac49"
          renderTabBar={() => (
            <TabBar underlineColor="#53ac49" activeTabTextStyle={{ color: "#53ac49" }} />
          )}
        >
              {this.state.arrayWithMyData.map(this.renderTab)}
        </ScrollableTabView>
```
Where `this.state.arrayWithMyData` contains all your data . you need to render tab. You can dynamically add data to array and it will produce new tabs.

**Comment by mozamonkey** [comment]
Could I have multiple tabs with code? How would that look?

**Comment by Slowyn** [comment]
Well, that would look like I showed above. You can check out [examples here](https://github.com/Slowyn/UnderlineTabBarExample).
Or read the documentation for [ScrollableTabView](https://github.com/happypancake/react-native-scrollable-tab-view)

**Comment by mozamonkey** [comment]
Are there any guides or boilerplates for me to plug in my code <View> //code </View> so it will be displayed on my ScrollableTabView?

**Comment by Slowyn** [comment]
Yeah, sure. React community has a lot of learning resources. Are you a newbie in React, right?
Honestly, I'm still didn't get the problem you are asking about and I can't get level of your proficiency. 
Let me show you an example of dynamical generating of new tabs.
```js
class App extends React.Component {
  state = {
    numberOfTabs: 3,
   };
   increment = () => this.setState({numberOfTabs: ++this.state.numberOfTabs});
   render() {
    const {numberOfTabs} = this.state;
    const tabs = [];
    for (let i = 0; i < numberOfTabs; i++) {
       tabs.push(i); // Here we create an array with data whic depends on state
       // if it depends on state it will rerender on each state change
       // You also can use props
       // The best place to know this principles closer is React Documentation
    }

    return (
       <View>
          <TouchableOpacity onPress={this.increment}><Text>Increment</Text></TouchableOpacity>
          <ScrollableTabView
            tabBarUnderlineColor="#53ac49"
            tabBarActiveTextColor="#53ac49"
            renderTabBar={() => (
              <TabBar underlineColor="#53ac49" activeTabTextStyle={{ color: "#53ac49" }} />
            )}
          >
             {/* Here we transform our array into views */}
             {tabs.map(n => <Text key={n}>{n}</Text>)}
          </ScrollableTabView>
       </View>
     );
  }
}
```

**Comment by mozamonkey** [comment]
Are there any samples you've seen of this library being implemented so I can get a better diea?

**Comment by Slowyn** [comment]
You can check out [examples here](https://github.com/Slowyn/UnderlineTabBarExample).
Or read the documentation for [ScrollableTabView](https://github.com/happypancake/react-native-scrollable-tab-view). Reading is often a helpful thing 😉
