### ISSUE TITLE
Rendering initial tab other tab first tab

### ISSUE THREAD

**Issue by syedirfan33** [Slowyn/react-native-underline-tabbar#42]
Thanks for contributing for react-native-underline-tabbar. I am making use of the library currently. could you please let me know how can I setup an initial tab other than first tab when my screen rendered?

I hope I won't be bothering you much. Kindly revert. Thank you in advance.

**Comment by zjxiaohan** [comment]
This tab bar is a custom tab bar for https://github.com/skv-headless/react-native-scrollable-tab-view . Therefore, you could go to the documentation for `react-native-scrollable-tab-view` for more information.

For your specific question, please take a look at the `initialPage` prop in https://github.com/ptomasroos/react-native-scrollable-tab-view#props

**Comment by syedirfan33** [comment]
Thank you so much for the prompt response.
