### ISSUE TITLE
Current NPM release has incorrect entry point in package.json

### ISSUE THREAD

**Issue by jarseneault** [Slowyn/react-native-underline-tabbar#6]
As mentioned, in package.json on the current NPM release, there is this:

`"main": "TabBar.js",`

while the actual file in the package is `tabBar.js`, causing various Module Not Found errors when it's imported.

It looks like the current Github version has this fixed (`tabBar.js` was renamed to `TabBar.js` in a later commit), so please sync the npm package to your Github.  Thanks!

**Comment by Slowyn** [comment]
Thanks for reporting! I've published new release.
