### ISSUE TITLE
item不能超过10个否则报错inputRange must be monotonically increasing 0,1,2,3,4,5,6,7,8,9,10

### ISSUE THREAD

**Issue by jackuhan** [Slowyn/react-native-underline-tabbar#7]
inputRange must be monotonically increasing 0,1,2,3,4,5,6,7,8,9,10
严重bug

**Comment by Slowyn** [comment]
Thank you for responding the issue. But could you provide more details?
Also PR's are welcome!

**Comment by Slowyn** [comment]
Couldn't reproduce.
